### ISSUE TITLE
sign up後にログインしようとすると弾かれる

### ISSUE THREAD

**Issue by satabie** [Pre-Hatching-Engineer/scanglish#6]
2024-06-30 00:02:32.642 Uncaught app exception
Traceback (most recent call last):
  File "/Users/iwasakimao/workspace/scanglish/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 589, in runscript
    exec(code, module.__dict)
  File "/Users/iwasakimao/workspace/scanglish/src/app.py", line 45, in <module>
    main()
  File "/Users/iwasakimao/workspace/scanglish/src/app.py", line 15, in main
    authenticate()
  File "/Users/iwasakimao/workspace/scanglish/src/auth.py", line 18, in authenticate
    if check_user(username, hash_password(password)):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/iwasakimao/workspace/scanglish/src/database.py", line 50, in check_user
    cursor.close()
    ^^^^^^

**Comment by satabie** [comment]
エンターでもログインしたい

**Comment by satabie** [comment]
解決
